### ISSUE TITLE
Increase travel speed during auto home

### ISSUE THREAD

**Issue by krisnoble** [LittleHobbyShop/SunluS8#1]
Is it possible to make the axes move faster during the auto home process please? It's one of the most annoying things I've found with the S8, the slow speed makes the process feel interminable, especially if you're doing the bed level a few times to get things perfect.

**Comment by krisnoble** [comment]
Sorry, realised it's actually the auto home that's slow so have edited the title and comment but Github seems to be having an issue updating the title...

**Comment by LittleHobbyShop** [comment]
Agreed, will adjust for the next update.
