### ISSUE TITLE
16 point bed leveling

### ISSUE THREAD

**Issue by Kedryn** [LittleHobbyShop/SunluS8#6]
Hi, not really an issue, but a request.
Can we have a 16 point bed leveling?
I've found out that my glass bed is pretty warped (don't ask me why, i don't know) and a 4 point bed leveling is not enough.

**Comment by LittleHobbyShop** [comment]
I have seen some people have issues with slightly warped glass beds but I think the vast majority of S8 users either haven't had a problem or have replaced the glass.
I'll leave the issue open and see if it garners any more interest, if so I can put out a version with extra points alongside the 4 point one.

**Comment by mike-8502** [comment]
I have 2 S8 printers, the glass had issues on both. One was worse than the other. The glass had a 'dip' or a 'hill' in the middle, depending on which side you used. I switched to 12"x12" mirror tiles (~305mmx305mm) available at my local home center. This solved the 'warped bed' issue for me. I run the 4 point level corners 3 to four times then run a calibration print to 'fine tune'.

**Comment by LittleHobbyShop** [comment]
!6 point mesh released.
